apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-node
  namespace: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.nodesPerCluster }}
  podManagementPolicy: Parallel
  template:
    metadata:
      namespace: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
      labels:
        app: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: node
      annotations:
        checksum/config: {{ toYaml .Values.config | sha256sum }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-node
        image: "{{ .Values.node.image.repository }}:{{ tpl .Values.node.image.tag . }}"
        imagePullPolicy: {{ .Values.node.image.pullPolicy }}
        args:
{{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 8 }}
{{- end }}
        env:
        - name: ROLE
          value: node
        - name: CLUSTER_TYPE
          value: primary
{{- range $key, $value := .Values.extraVars }}
        - name: {{ $key }}
          value: {{ $value }}
{{- end }}
        # See https://gravitational.com/teleport/docs/admin-guide/#ports
        ports:
{{- range $key, $port := .Values.ports.node }}
        - name: {{ $key }}
{{ toYaml $port | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/teleport
          name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-node-config
          readOnly: true
        - mountPath: /var/lib/teleport
          name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-storage
        - mountPath: /var/lib/tokens/node
          name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-node-join-token
        - mountPath: /var/lib/tokens/ca-pin
          name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-ca-pin
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
      - name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-node-config
        configMap:
          name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-node-config
      - name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-storage
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s-%s" (include "teleport.fullname" .) .Values.mainClusterName "storage") }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-node-join-token
        secret:
          secretName: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-node-join-token
      - name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-ca-pin
        secret:
          secretName: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-ca-pin
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
{{- if .Values.node.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.node.image.pullSecrets | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
      serviceAccountName: {{ template "teleport.serviceAccountName" . }}-{{ .Values.mainClusterName }}

{{- if not (eq (index .Values.extraClusterNames 0) "") -}}
{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "teleport.fullname" $root }}-{{ . }}-node
  namespace: {{ template "teleport.fullname" $root }}-{{ . }}
  labels:
{{ include "teleport.labels" $root | indent 4 }}
{{- if $root.Values.labels }}
{{ toYaml $root.Values.labels | indent 4 }}
{{- end }}
spec:
  replicas: {{ $root.Values.nodesPerCluster }}
  podManagementPolicy: Parallel
  template:
    metadata:
      namespace: {{ template "teleport.fullname" $root }}-{{ . }}
      labels:
        app: {{ template "teleport.fullname" $root }}-{{ . }}
        release: {{ $root.Release.Name }}
        heritage: {{ $root.Release.Service }}
        role: node
      annotations:
        checksum/config: {{ toYaml $root.Values.config | sha256sum }}
{{- if $root.Values.annotations }}
{{ toYaml $root.Values.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ template "teleport.fullname" $root }}--{{ . }}-node
        image: "{{ $root.Values.node.image.repository }}:{{ tpl $root.Values.node.image.tag $root }}"
        imagePullPolicy: {{ $root.Values.node.image.pullPolicy }}
        args:
{{- if $root.Values.extraArgs }}
{{ toYaml $root.Values.extraArgs | indent 8 }}
{{- end }}
        env:
        - name: ROLE
          value: node
        - name: CLUSTER_TYPE
          value: secondary
{{- range $key, $value := $root.Values.extraVars }}
        - name: {{ $key }}
          value: {{ $value }}
{{- end }}
        # See https://gravitational.com/teleport/docs/admin-guide/#ports
        ports:
{{- range $key, $port := $root.Values.ports.node }}
        - name: {{ $key }}
{{ toYaml $port | indent 10 }}
{{- end }}
        resources:
{{ toYaml $root.Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/teleport
          name: {{ template "teleport.fullname" $root }}-{{ . }}-node-config
          readOnly: true
        - mountPath: /var/lib/teleport
          name: {{ template "teleport.fullname" $root }}-{{ . }}-storage
        - mountPath: /var/lib/tokens/node
          name: {{ template "teleport.fullname" $root }}-{{ . }}-node-join-token
        - mountPath: /var/lib/tokens/ca-pin
          name: {{ template "teleport.fullname" $root }}-{{ . }}-ca-pin
{{- if $root.Values.extraVolumeMounts }}
{{ toYaml $root.Values.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
      - name: {{ template "teleport.fullname" $root }}-{{ . }}-node-config
        configMap:
          name: {{ template "teleport.fullname" $root }}-{{ . }}-node-config
      - name: {{ template "teleport.fullname" $root }}-{{ . }}-storage
        {{- if $root.Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ $root.Values.persistence.existingClaim | default (printf "%s-%s-%s" (include "teleport.fullname" $root) . "storage") }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: {{ template "teleport.fullname" $root }}-{{ . }}-node-join-token
        secret:
          secretName: {{ template "teleport.fullname" $root }}-{{ . }}-node-join-token
      - name: {{ template "teleport.fullname" $root }}-{{ . }}-ca-pin
        secret:
          secretName: {{ template "teleport.fullname" $root }}-{{ . }}-ca-pin
{{- if $root.Values.extraVolumes }}
{{ toYaml $root.Values.extraVolumes | indent 6 }}
{{- end }}
{{- if $root.Values.node.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml $root.Values.node.image.pullSecrets | indent 6 }}
{{- end }}
{{- if $root.Values.affinity }}
      affinity:
{{ toYaml $root.Values.affinity | indent 8 }}
{{- end }}
{{- if $root.Values.tolerations }}
      tolerations:
{{ toYaml $root.Values.tolerations | indent 6 }}
{{- end }}
      serviceAccountName: {{ template "teleport.serviceAccountName" $root }}-{{ . }}
{{- end -}}
{{- end }}