apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  labels:
{{ include "teleport.labels" .| indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"

{{- if not (eq (index .Values.extraClusterNames 0) "") -}}
{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "teleport.fullname" $root }}-{{ . }}
  labels:
{{ include "teleport.labels" $root | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
{{- end -}}
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: namespace-cleaner
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: namespace-cleaner
    spec:
      containers:
      - name: namespace-cleaner
        image: {{ .Values.namespacecleaner.image.repository }}:{{ tpl .Values.namespacecleaner.image.tag . }}
        imagePullPolicy: {{ .Values.namespacecleaner.image.pullPolicy }}
        args:
        - {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
        {{- if not (eq (index .Values.extraClusterNames 0) "") -}}
        {{- $root := . -}}
        {{- range .Values.extraClusterNames }}
        - {{ template "teleport.fullname" $root }}-{{ . }}
        {{- end -}}
        {{- end }}
      restartPolicy: Never
{{- if .Values.namespacecleaner.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.namespacecleaner.image.pullSecrets | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
      serviceAccountName: {{ template "teleport.serviceAccountName" . }}-cleaner
  backoffLimit: 0