{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}-storage
  namespace: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}

{{- if not (eq (index .Values.extraClusterNames 0) "") -}}
{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "teleport.fullname" $root }}-{{ . }}-storage
  namespace: {{ template "teleport.fullname" $root }}-{{ . }}
  labels:
{{ include "teleport.labels" $root | indent 4 }}
{{- if $root.Values.persistence.annotations }}
  annotations:
{{ toYaml $root.Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ $root.Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ $root.Values.persistence.storageSize | quote }}
{{- if $root.Values.persistence.storageClass }}
{{- if (eq "-" $root.Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $root.Values.persistence.storageClass }}"
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}
