apiVersion: v1
kind: Service
metadata:
  name: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  namespace: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if contains "LoadBalancer" .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end -}}
  {{- else }}
  ports:
  {{- range $key, $value := .Values.nodePort.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
    release: {{ .Release.Name }}
    role: auth

{{- if not (eq (index .Values.extraClusterNames 0) "") -}}
{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "teleport.fullname" $root }}-{{ . }}
  namespace: {{ template "teleport.fullname" $root }}-{{ . }}
  labels:
{{ include "teleport.labels" $root | indent 4 }}
{{- if $root.Values.service.labels }}
{{ toYaml $root.Values.service.annotations | indent 4 }}
{{- end }}
{{- if $root.Values.service.annotations }}
  annotations:
{{ toYaml $root.Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ $root.Values.service.type }}
  {{- if contains "LoadBalancer" $root.Values.service.type }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
  {{- range $key, $value := $root.Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    app: {{ template "teleport.fullname" $root }}-{{ . }}
    release: {{ $root.Release.Name }}
    role: auth
{{- end -}}
{{- end }}
