{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport.serviceAccountName" . }}-cleaner
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport.serviceAccountName" . }}-{{ .Values.mainClusterName }}
  namespace: {{ template "teleport.fullname" . }}-{{ .Values.mainClusterName }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets | indent 2 }}
{{- end }}

{{- if not (eq (index .Values.extraClusterNames 0) "") -}}
{{- $root := . -}}
{{- range .Values.extraClusterNames }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport.serviceAccountName" $root }}-{{ . }}
  namespace: {{ template "teleport.fullname" $root }}-{{ . }}
  labels:
{{ include "teleport.labels" $root | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- if $root.Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml $root.Values.serviceAccount.imagePullSecrets | indent 2 }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}